// Generated by CoffeeScript 1.9.2
(function() {
  var couchdb, createBundle, database, dbName, expect, fixtures, takeMeasure;

  expect = require('must');

  couchdb = require('mock-couch').createServer();

  createBundle = require('../../../openbeelab-db-admin/javascript/create_bundle');

  fixtures = require('./fixtures');

  takeMeasure = require('../takeMeasure');

  couchdb.listen(5985);

  dbName = 'test_db';

  couchdb.addDB(dbName + '_config');

  couchdb.addDB(dbName + '_data');

  database = {
    host: 'localhost',
    protocol: 'http',
    port: 5985
  };

  describe("taking measure with a roman scale", function() {
    return it("should work (with a mock device)", function() {
      var device, result, sensor;
      device = require('../devices/' + fixtures.stand.device);
      device.analogWrite('in_voltage0_raw', 195);
      device.analogWrite('in_voltage1_raw', 205);
      sensor = fixtures.stand.sensors[0];
      sensor.device = device;
      result = takeMeasure(sensor);
      expect(result).to.not.be["null"]();
      return result.raw_value.must.be.number();
    });
  });

}).call(this);
