// Generated by CoffeeScript 1.9.2
(function() {
  var expect, fixtures, takeMeasure;

  expect = require('must');

  fixtures = require('./fixtures');

  takeMeasure = require('../takeMeasure');

  describe("taking measure with a roman scale", function() {
    return it("should work", function() {
      var device, result, sensor;
      device = require('../devices/' + fixtures.stand.device);
      device.analogWrite('in_voltage0_raw', 195);
      device.analogWrite('in_voltage1_raw', 205);
      sensor = fixtures.stand.sensors[0];
      sensor.device = device;
      result = takeMeasure(sensor);
      expect(result).to.not.be["null"]();
      return result.raw_value.must.be.a.number();
    });
  });

}).call(this);
