// Generated by CoffeeScript 1.9.2
(function() {
  var config, dataDb, dbDriver, dbServer, expect, fixtures, saveMeasure;

  expect = require('must');

  fixtures = require('./fixtures');

  saveMeasure = require('../saveMeasure');

  config = require('../config');

  dbDriver = require('../../../openbeelab-db-util/javascript/mockDriver');

  dbServer = dbDriver.connectToServer(config.database);

  dataDb = dbServer.useDb(config.name + "_data");

  describe("saving measure", function() {
    return it("should work", function(done) {
      var device, measure, sensor;
      device = require('../devices/' + fixtures.stand.device);
      sensor = fixtures.stand.sensors[0];
      sensor.device = device;
      measure = {
        type: 'measure',
        value: 321.54,
        name: 'global-weight'
      };
      saveMeasure(measure, fixtures.stand, dataDb);
      return done();
    });
  });

}).call(this);
