// Generated by CoffeeScript 1.9.2
(function() {
  var Pin, sleep;

  require('../../../openbeelab-util/javascript/arrayUtils').install();

  require('../../../openbeelab-util/javascript/numberUtils').install();

  sleep = require('../../../openbeelab-util/javascript/timeUtils').sleep;

  Pin = require('./pin');

  module.exports = function(device, config) {
    var direction, enable, ms1, ms2, ms3, pulse, reset, sleepPin;
    enable = Pin.buildGpio(device, config.enable, 'out');
    ms1 = Pin.buildGpio(device, config.ms1, 'out');
    ms2 = Pin.buildGpio(device, config.ms2, 'out');
    ms3 = Pin.buildGpio(device, config.ms3, 'out');
    pulse = Pin.buildGpio(device, config.pulse, 'out');
    direction = Pin.buildGpio(device, config.direction, 'out');
    sleepPin = Pin.buildGpio(device, config.sleep, 'out');
    reset = Pin.buildGpio(device, config.reset, 'out');
    ms1.setOff();
    ms2.setOff();
    ms3.setOff();
    return {
      switchOn: function() {
        enable.setOff();
        reset.setOn();
        sleepPin.setOn();
        return sleep(1);
      },
      switchOff: function() {
        enable.setOn();
        reset.setOff();
        return sleepPin.setOff();
      },
      forward: function(nbSteps) {
        if (nbSteps == null) {
          nbSteps = 1;
        }
        return this.move(nbSteps);
      },
      backward: function(nbSteps) {
        if (nbSteps == null) {
          nbSteps = 1;
        }
        return this.move(-1 * nbSteps);
      },
      move: function(nbSteps) {
        var goForward;
        if (nbSteps == null) {
          nbSteps = 1;
        }
        goForward = nbSteps > 0;
        nbSteps = nbSteps.abs();
        direction.setValue(goForward);
        nbSteps.times(function() {
          pulse.setOn();
          sleep(config.stepDelay);
          pulse.setOff();
          return sleep(config.stepDelay);
        });
      }
    };
  };

}).call(this);
