// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    host: 'localhost',
    protocol: 'http',
    port: 5984,
    db: 'la_mine_dev',
    apiary_name: 'la_mine_rucher_01'
  };

}).call(this);
