// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    host: 'dev.openbeelab.org',
    protocol: 'http',
    port: 5984,
    auth: {
      username: 'user_name',
      password: 'user_pass'
    },
    name: 'db_name',
    stand_id: 'stand:socle_001'
  };

}).call(this);
