// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    host: 'localhost',
    protocol: 'http',
    port: 5984,
    auth: {
      username: 'admin',
      password: 'c0uchAdm1n'
    },
    name: 'la_mine_dev',
    stand_id: 'stand:protopierre_001'
  };

}).call(this);
