// Generated by CoffeeScript 1.9.2
(function() {
  var device, measure, sensor, specificProcess;

  sensor = {
    device: 'arietta_g25',
    process: 'romanScale',
    action: 'searchEquilibrium',
    motor: {
      enable: 'J4.8',
      ms1: 'J4.10',
      ms2: 'J4.12',
      ms3: 'J4.14',
      pulse: 'J4.28',
      direction: 'J4.30',
      sleep: 'J4.26',
      reset: 'J4.24'
    },
    photoDiode1: 'in_voltage0_raw',
    photoDiode2: 'in_voltage1_raw',
    deltaTarget: 0
  };

  device = require('./devices/' + sensor.device);

  specificProcess = require('./' + sensor.process);

  measure = specificProcess(sensor, device)[sensor.action];

  console.log(measure());

}).call(this);
