// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(db, sensor, location, value, callback) {
    var measure;
    if (callback == null) {
      callback = function() {};
    }
    measure = {
      timestamp: new Date(),
      location_id: location._id,
      beehouse_id: sensor.beehouse_id,
      type: 'measure',
      name: sensor.name,
      raw_value: value,
      value: (value - sensor.bias) * sensor.gain,
      unit: sensor.unit
    };
    return db.save(measure, callback);
  };

}).call(this);
