// Generated by CoffeeScript 1.9.2
(function() {
  var config, configDb, dataDb, dbDriver, dbServer, saveMeasure, weight;

  config = require('./config');

  saveMeasure = require('./saveMeasure');

  dbDriver = require('../../openbeelab-db-util/javascript/dbDriver');

  dbServer = dbDriver.connectToServer(dbConfig.database);

  configDb = dbServer.useDb(config.database.name + "_config");

  dataDb = dbServer.useDb(config.database.name + "_data");

  weight = 0;

  configDb.get(config.stand_id).then(function(stand) {
    var measure;
    measure = {
      type: 'measure',
      name: 'global-weight',
      value: weight,
      unit: 'Kg',
      measureSource: "manual",
      timestamp: new Date(),
      location_id: stand.location_id,
      beehouse_id: stand.beehouse_id,
      stand_id: stand._id
    };
    return saveMeasure(measure, dataDb);
  })["catch"](function(err) {
    return console.log(err);
  });

}).call(this);
