// Generated by CoffeeScript 1.9.2
(function() {
  var config, db, dbDriver, insert_measure;

  dbDriver = require('../../openbeelab-db-util/javascript/dbUtil');

  config = require('./config');

  db = dbDriver.database(config);

  insert_measure = require('./insert_measure');

  db.get(config.stand_id).then(function(stand) {
    var device, i, len, measure, ref, sensor, specificProcess, value;
    device = require('./devices/' + stand.device);
    ref = stand.sensors;
    for (i = 0, len = ref.length; i < len; i++) {
      sensor = ref[i];
      if (!sensor.active) {
        continue;
      }
      sensor.device = device;
      if (device[sensor.process] != null) {
        measure = device[sensor.process];
      } else {
        specificProcess = require('./' + sensor.process);
        measure = specificProcess(sensor, device)[sensor.action];
      }
      value = measure(sensor, device);
      console.log(value);
      measure = {
        timestamp: new Date(),
        location_id: stand.location_id,
        beehouse_id: stand.beehouse_id,
        type: 'measure',
        name: sensor.name,
        raw_value: value,
        value: (value - sensor.bias) * sensor.gain,
        unit: sensor.unit
      };
      db.save(measure).then(function() {
        return console.log("measure uploaded to db " + config.name);
      });
    }
    if (stand.sleepMode === true && device.planWakeup && device.shutdown) {
      device.planWakeup(10);
      console.log("system will reboot 10 seconds after shutdown");
      device.shutdown();
      return console.log("system is going to shutdown...");
    }
  })["catch"](function(err) {
    return console.log(err);
  });

}).call(this);
