// Generated by CoffeeScript 1.9.2
(function() {
  var config, db, dbDriver, insert_measure;

  dbDriver = require('../../openbeelab-db-util/javascript/dbUtil');

  config = require('./config');

  db = dbDriver.database(config);

  insert_measure = require('./insert_measure');

  db.get(config.stand_id).then(function(stand) {
    var device, i, len, measure, measurePromise, ref, results, sensor;
    device = require('./devices/' + stand.device);
    ref = stand.sensors;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      sensor = ref[i];
      if (device[sensor.type] == null) {
        measure = require("./" + sensor.type);
      } else {
        measure = device[sensor.type];
      }
      measurePromise = measure(sensor, device);
      results.push(measurePromise.then(function(value) {
        console.log(value);
        measure = {
          timestamp: new Date(),
          location_id: stand.location_id,
          beehouse_id: stand.beehouse_id,
          type: 'measure',
          name: sensor.name,
          raw_value: value,
          value: value,
          unit: sensor.unit
        };
        return db.save(measure).then(function() {
          return console.log("measure uploaded to db " + config.name);
        });
      })["catch"](function(err) {
        return console.log(err);
      }));
    }
    return results;
  })["catch"](function(err) {
    return console.log(err);
  });

}).call(this);
