// Generated by CoffeeScript 1.9.2
(function() {
  var apiariesPromise, apiariesUrl, apiary, apiaryLocation, db, dbConfig, dbDriver, insert_measure;

  dbDriver = require('../../openbeelab-db-util/javascript/dbUtil');

  dbConfig = require('./config');

  db = dbDriver.database(dbConfig);

  insert_measure = require('./insert_measure');

  apiary = null;

  apiaryLocation = null;

  apiariesUrl = '_design/apiaries/_view/by_name?key="' + dbConfig.apiary_name + '"';

  apiariesPromise = db.get(apiariesUrl);

  apiariesPromise.then(function(apiaries) {
    apiary = apiaries[0].value;
    return db.get(apiary.location_id);
  }).then(function(location) {
    var beehousesUrl;
    apiaryLocation = location;
    console.log(location);
    beehousesUrl = '_design/beehouses/_view/by_apiary?key="' + apiary._id + '"';
    return db.get(beehousesUrl);
  }).then(function(beehouses) {
    var beehouse, i, len, results, sensorsPromise, sensorsUrl;
    console.log(beehouses);
    results = [];
    for (i = 0, len = beehouses.length; i < len; i++) {
      beehouse = beehouses[i];
      beehouse = beehouse.value;
      sensorsUrl = '_design/sensors/_view/by_beehouse?key="' + beehouse._id + '"';
      sensorsPromise = db.get(sensorsUrl);
      results.push(sensorsPromise.then(function(sensors) {
        var device, j, len1, measurePromise, results1, sensor;
        results1 = [];
        for (j = 0, len1 = sensors.length; j < len1; j++) {
          sensor = sensors[j];
          console.log(sensor);
          sensor = sensor.value;
          device = require('./devices/' + sensor["device"]);
          measurePromise = device.use(sensor);
          results1.push(measurePromise.then(function(value) {
            var insertPromise;
            console.log(value);
            insertPromise = insert_measure(db, sensor, apiaryLocation, value);
            return insertPromise.then(function(msg) {
              console.log(msg);
              return console.log("measure uploaded to db " + dbConfig.db);
            });
          }));
        }
        return results1;
      })["catch"](function(err) {
        return console.log(err);
      }));
    }
    return results;
  })["catch"](function(err) {
    return console.log(err);
  });

}).call(this);
