// Generated by CoffeeScript 1.9.2
(function() {
  var config, db, dbDriver;

  console.log("executing plan_reboot.js...");

  dbDriver = require('../../openbeelab-db-util/javascript/dbUtil');

  config = require('./config');

  config.name = config.name + "_config";

  db = dbDriver.database(config);

  db.get(config.stand_id).then(function(stand) {
    var device;
    device = require('./devices/' + stand.device);
    return [stand.sleepMode === true && device.planWakeup && device.shutdown, stand.sleepDuration, device];
  })["catch"](function(err) {
    var device;
    console.log("error while fetching sleep infos in db:");
    console.log(err);
    device = null;
    try {
      return device = require('./devices/arietta_g25');
    } finally {
      return [true, 3300, device];
    }
  })["finally"](function(arg) {
    var device, sleepDuration, sleepMode;
    sleepMode = arg[0], sleepDuration = arg[1], device = arg[2];
    if (sleepMode && (device != null)) {
      device.planWakeup(sleepDuration);
      console.log("system will reboot " + sleepDuration + " seconds after shutdown");
      device.shutdown();
      return console.log("system is going to shutdown...");
    }
  });

}).call(this);
