// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(measure, stand, dataDb) {
    return dataDb.save(measure).then(function(result) {
      console.log("measure uploaded to db " + dataDbOptions.name);
      console.log("measure id:" + result._id);
      return dataDb.save({
        _id: "_design/updates/_update/time/" + result._id
      });
    }).then(function() {
      return console.log("added server timestamp");
    });
  };

}).call(this);
