// Generated by CoffeeScript 1.9.2
(function() {
  var device, ledGround, ledPlus, sensor;

  sensor = {
    device: "arietta_g25",
    measureType: 'analogRead',
    pinName: "in_voltage0_raw"
  };

  ledPlus = {
    device: "arietta_g25",
    measureType: 'digitalWrite',
    direction: "out",
    pinName: "pioB14",
    value: 1
  };

  ledGround = {
    device: "arietta_g25",
    measureType: 'digitalWrite',
    direction: "out",
    pinName: "pioB13",
    value: 0
  };

  device = require('./devices/' + sensor.device);

  device.use(sensor).then(function(value) {
    console.log("value:" + value);
    return device.use(ledPlus, ledPlus.value).then(function() {
      return device.use(ledGround, ledGround.value).then(function() {
        return device.use(sensor).then(function(value) {
          return console.log("value:" + value);
        });
      });
    });
  })["catch"](function(err) {
    return console.log(err);
  });

}).call(this);
