// Generated by CoffeeScript 1.9.2
(function() {
  var api, pin2kid, pin2name, sh;

  sh = require('execSync');

  pin2name = {
    'J4.7': 'PA23',
    'J4.8': 'PA22',
    'J4.10': 'PA21',
    'J4.11': 'PA24',
    'J4.12': 'PA31',
    'J4.13': 'PA25',
    'J4.14': 'PA30',
    'J4.15': 'PA26',
    'J4.17': 'PA27',
    'J4.19': 'PA28',
    'J4.21': 'PA29',
    'J4.23': 'PA0',
    'J4.24': 'PA1',
    'J4.25': 'PA8',
    'J4.26': 'PA7',
    'J4.27': 'PA6',
    'J4.28': 'PA5',
    'J4.29': 'PC28',
    'J4.30': 'PC27',
    'J4.31': 'PC4',
    'J4.32': 'PC31',
    'J4.33': 'PC3',
    'J4.34': 'PB11',
    'J4.35': 'PC2',
    'J4.36': 'PB12',
    'J4.37': 'PC1',
    'J4.38': 'PB13',
    'J4.39': 'PC0',
    'J4.40': 'PB14'
  };

  pin2kid = {
    'J4.7': 55,
    'J4.8': 54,
    'J4.10': 53,
    'J4.11': 56,
    'J4.12': 63,
    'J4.13': 57,
    'J4.14': 62,
    'J4.15': 58,
    'J4.17': 59,
    'J4.19': 60,
    'J4.21': 61,
    'J4.23': 32,
    'J4.24': 33,
    'J4.25': 40,
    'J4.26': 39,
    'J4.27': 38,
    'J4.28': 37,
    'J4.29': 124,
    'J4.30': 123,
    'J4.31': 100,
    'J4.32': 127,
    'J4.33': 99,
    'J4.34': 75,
    'J4.35': 98,
    'J4.36': 76,
    'J4.37': 97,
    'J4.38': 77,
    'J4.39': 96,
    'J4.40': 78
  };

  api = {
    "export": function(pinName) {
      return fs.writeFileSync("/sys/class/gpio/export", "" + pin2kid[pinName]);
    },
    unexport: function(pinName) {
      return fs.writeFileSync("/sys/class/gpio/unexport", pin2kid[pinName]);
    },
    getDirection: function(pinName) {
      return fs.readFileSync("/sys/class/gpio/" + pin2name[pinName] + "/direction");
    },
    setDirection: function(pinName, direction) {
      return fs.writeFileSync("sys/class/gpio/" + pin2name[pinName] + "/direction", direction);
    },
    setInputMode: function(pinName) {
      return this.setDirection(pinName, "in");
    },
    setOutputMode: function(pinName) {
      return this.setDirection(pinName, "out");
    },
    digitalRead: function(pinName) {
      var value;
      value = fs.readFileSync("/sys/class/gpio/" + pin2name[pinName] + "/value");
      if (value === "0") {
        return false;
      }
      return true;
    },
    digitalWrite: function(pinName, value) {
      if (value === true) {
        value = "1";
      }
      if (value === false) {
        value = "0";
      }
      return fs.writeFileSync("/sys/class/gpio/" + pin2name[pinName] + "/value", value);
    },
    analogRead: function(adcName) {
      return fs.readFileSync("/sys/bus/iio/devices/iio:device0/" + adcName).toInt();
    },
    planWakeup: function(seconds) {
      return fs.writeFileSync("/sys/class/rtc/rtc0/wakealarm", "" + seconds);
    },
    sleep: function() {
      return sh.exec("halt");
    }
  };

  module.exports = api;

}).call(this);
