// Generated by CoffeeScript 1.9.2
(function() {
  var api, fs, pin2kid, pin2name;

  fs = require('fs');

  pin2name = {
    'J4.7': 'PA23',
    'J4.8': 'PA22',
    'J4.10': 'PA21',
    'J4.11': 'PA24',
    'J4.12': 'PA31',
    'J4.13': 'PA25',
    'J4.14': 'PA30',
    'J4.15': 'PA26',
    'J4.17': 'PA27',
    'J4.19': 'PA28',
    'J4.21': 'PA29',
    'J4.23': 'PA0',
    'J4.24': 'PA1',
    'J4.25': 'PA8',
    'J4.26': 'PA7',
    'J4.27': 'PA6',
    'J4.28': 'PA5',
    'J4.29': 'PC28',
    'J4.30': 'PC27',
    'J4.31': 'PC4',
    'J4.32': 'PC31',
    'J4.33': 'PC3',
    'J4.34': 'PB11',
    'J4.35': 'PC2',
    'J4.36': 'PB12',
    'J4.37': 'PC1',
    'J4.38': 'PB13',
    'J4.39': 'PC0',
    'J4.40': 'PB14'
  };

  pin2kid = {
    'J4.7': 23,
    'J4.8': 22,
    'J4.10': 21,
    'J4.11': 24,
    'J4.12': 31,
    'J4.13': 25,
    'J4.14': 30,
    'J4.15': 26,
    'J4.17': 27,
    'J4.19': 28,
    'J4.21': 29,
    'J4.23': 0,
    'J4.24': 1,
    'J4.25': 8,
    'J4.26': 7,
    'J4.27': 6,
    'J4.28': 5,
    'J4.29': 92,
    'J4.30': 91,
    'J4.31': 68,
    'J4.32': 95,
    'J4.33': 67,
    'J4.34': 43,
    'J4.35': 66,
    'J4.36': 44,
    'J4.37': 65,
    'J4.38': 45,
    'J4.39': 64,
    'J4.40': 46
  };

  api = {
    "export": function(pinName) {
      return fs.writeFileSync("/sys/class/gpio/export", "" + pin2kid[pinName]);
    },
    unexport: function(pinName) {
      return fs.writeFileSync("/sys/class/gpio/unexport", pin2kid[pinName]);
    },
    getDirection: function(pinName) {
      return fs.readFileSync("/sys/class/gpio/" + pin2name[pinName] + "/direction");
    },
    setDirection: function(pinName, direction) {
      return fs.writeFileSync("sys/class/gpio/" + pin2name[pinName] + "/direction", direction);
    },
    setInputMode: function(pinName) {
      return this.setDirection(pinName, "in");
    },
    setOutputMode: function(pinName) {
      return this.setDirection(pinName, "out");
    },
    digitalRead: function(pinName) {
      var value;
      value = fs.readFileSync("/sys/class/gpio/" + pin2name[pinName] + "/value");
      if (value === "0") {
        return false;
      }
      return true;
    },
    digitalWrite: function(pinName, value) {
      if (value === true) {
        value = "1";
      }
      if (value === false) {
        value = "0";
      }
      return fs.writeFileSync("/sys/class/gpio/" + pin2name[pinName] + "/value", value);
    },
    analogRead: function(adcName) {
      value = "" + fs.readFileSync("/sys/bus/iio/devices/iio:device0/" + adcName)
      return value.toInt();
    },
    planWakeup: function(seconds) {
      return fs.writeFileSync("/sys/class/rtc/rtc0/wakealarm", "" + seconds);
    },
    sleep: function() {
      return sh.exec("halt");
    }
  };

  module.exports = api;

}).call(this);
