// Generated by CoffeeScript 1.9.2
(function() {
  var api;

  require('../../../openbeelab-util/javascript/arrayUtils').install();

  api = {
    "export": function(kernelId) {
      return "ok";
    },
    unexport: function(kernelId) {
      return "ok";
    },
    getDirection: function(kernelId) {
      return "in";
    },
    setDirection: function(kernelId, direction) {
      return "ok";
    },
    setInputMode: function(kernelId) {
      return "ok";
    },
    setOutputMode: function(kernelId) {
      return "ok";
    },
    digitalRead: function(pin) {
      return [true, false].pickRandom();
    },
    digitalWrite: function(pin, value) {
      return "ok";
    },
    analogRead: function(pin) {
      var i, results;
      return (function() {
        results = [];
        for (i = 0; i <= 1023; i++){ results.push(i); }
        return results;
      }).apply(this).pickRandom();
    }
  };

  module.exports = api;

}).call(this);
