// Generated by CoffeeScript 1.9.2
(function() {
  var api, values;

  require('../../../openbeelab-util/javascript/arrayUtils').install();

  values = {};

  api = {
    "export": function(kernelId) {
      return "ok";
    },
    unexport: function(kernelId) {
      return "ok";
    },
    getDirection: function(kernelId) {
      return "in";
    },
    setDirection: function(kernelId, direction) {
      return "ok";
    },
    setInputMode: function(kernelId) {
      return "ok";
    },
    setOutputMode: function(kernelId) {
      return "ok";
    },
    digitalRead: function(pin) {
      if (values[pin] == null) {
        values[pin] = [true, false].pickRandom();
      }
      return values[pin];
    },
    digitalWrite: function(pin, value) {
      var dir;
      if (pin === 'J4.28') {
        dir = values['J4.30'] ? 1 : -1;
        values['in_voltage0_raw'] -= 20 * dir;
        values['in_voltage1_raw'] += 20 * dir;
      }
      return values[pin] = value;
    },
    analogWrite: function(pin, value) {
      return values[pin] = value;
    },
    analogRead: function(pin) {
      var i, results;
      if (values[pin] == null) {
        values[pin] = (function() {
          results = [];
          for (i = 0; i <= 1023; i++){ results.push(i); }
          return results;
        }).apply(this).pickRandom();
      }
      return values[pin];
    }
  };

  module.exports = api;

}).call(this);
