// Generated by CoffeeScript 1.9.2
(function() {
  var sh;

  sh = require('execSync');

  exports.read = function(pin) {
    var command, result, value;
    command = 'python /home/ubuntu/openbeelab/uploader/javascript/readadc.py ' + pin;
    result = sh.exec(command);
    value = parseInt(result.stdout);
    return value;
  };

}).call(this);
