// Generated by CoffeeScript 1.9.2
(function() {
  var Promise, api, pcduino;

  pcduino = require('pcduino');

  Promise = require('promise');

  api = {
    use: function(sensor) {
      return this[sensor.measureType](sensor.pin);
    },
    digitalRead: function(pin) {
      return Promise.resolve(pcduino.digital.read(pin));
    },
    digitalWrite: function(pin, value) {
      return Promise.resolve(pcduino.digital.write(pin, value));
    },
    analogRead: function(pin, callback) {
      return Promise.resolve(pcduino.analog.read(pin));
    },
    pwm: function(value) {}
  };

  module.exports = api;

}).call(this);
